name: asvine
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2 #icon paketi
  flutter_screenutil: ^5.5.4 #sayfalarımızda “responsive height weight , fontsize” paketi.
  flutter_native_splash: ^2.2.10+1 #Splash screen paketi
  introduction_screen: ^3.0.1 #OnBoard screen paketi
  animated_text_kit: ^4.2.2 #text animasyon paketi

dev_dependencies:
  flutter_launcher_icons: ^0.10.0 #uygulama iconu paketi
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 #iyi kodlama uygulamalarını teşvik paketi

flutter_icons:
  image_path: "assets/icons/asvine.png"
  image_path_anroid: "assets/icons/asvine.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
     - assets/dialogs/
     - assets/fonts/
     - assets/icons/
     - assets/images/
     - assets/langs/
     - assets/logos/
     - assets/animated/

  fonts:
    - family: Flamenco
      fonts:
        - asset: assets/fonts/Flamenco-Light.ttf
        - asset: assets/fonts/Flamenco-Regular.ttf

